---
- name: "Install Homebrew Packages"
  community.general.homebrew:
    name: "{{ packages }}"
  vars:
    packages:
      - 'imagemagick'
      - 'youtube-dl'
      - 'youtubedr'
    state: present
    update_homebrew: yes
    upgrade_all: yes
  register: brew_common_result
  ignore_errors: true

- name: "Install Homebrew Cask Packages"
  community.general.homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
      # - 'signal'
      # - 'sling'
      # - 'anydesk'
      - 'barrier'
      - 'bitwarden'
      - 'discord'
      # - 'dropbox'
      - 'firefox'
      - 'font-hack-nerd-font'
      - 'gimp'
      - 'google-chat'
      - 'google-chrome'
      - 'google-drive'
      - 'keybase'
      - 'libreoffice'
      - 'maestral'
      - 'rar'
      - 'royal-tsx'
      - 'skype'
      - 'slack'
      - 'spotify'
      - 'telegram'
      - 'tor-browser'
      - 'vlc'
      - 'zoom'
    state: present
    upgrade_all: yes
    update_homebrew: yes
  register: brew_cask_desktop_result
  ignore_errors: true
  # failed_when: "'Error:' in brew_cask_desktop_result.stdout"

