---
- name: "Install Google Chrome with Homebrew Cask"
  community.general.homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
      - 'google-chrome'
    state: present
    upgrade_all: yes
    update_homebrew: yes
  register: brew_cask_desktop_chrome_result
  ignore_errors: true
  failed_when: "'Error:' in brew_cask_desktop_chrome_result.stdout"

- name: "Install Homebrew Cask Packages"
  community.general.homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
      - 'anydesk'
      - 'discord'
      - 'dropbox'
      - 'firefox'
      - 'font-hack-nerd-font'
      - 'gimp'
      - 'google-drive'
      - 'google-hangouts'
      - 'libreoffice'
      - 'royal-tsx'
      - 'signal'
      - 'skype'
      - 'slack'
      - 'sling'
      - 'spotify'
      - 'telegram'
      - 'tor-browser'
      - 'vlc'
      - 'zoom'
    state: present
    upgrade_all: yes
    update_homebrew: yes
  register: brew_cask_desktop_result
  ignore_errors: true
  failed_when: "'Error:' in brew_cask_desktop_result.stdout"

